project_name: nodepanels-daemon
before:
  hooks:
builds:
  - env:
      - CGO_ENABLED=0
    id: "nodepanels-daemon"
    binary: "nodepanels-daemon-{{ .Os }}-{{ .Arch }}"
    goos:
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  - format: binary